### ISSUE TITLE
Superuser app option duplication

### ISSUE THREAD

**Issue by CaptainThrowback** [seSuperuser/Superuser#1]
When opening phh's Superuser, and choosing the "Settings" option from the 3-dot menu, the Settings screen appears and has the same 3-dot menu. If you choose Settings from that menu, it opens Settings again, then if you press the Back button, all of the Settings options appear duplicated. Additionally, there is no Back button in the upper left to go back to the previous page/screen.

**Comment by lbdroid** [comment]
UI is definitely a work in progress, thank you for the report.

Depending on your device, either the triangle on your nav bar, or possibly (older devices) some dedicated button will be "back". This back button is a requirement for Android design compliance, if it is no present, please file a bug report with your device vendor.

**Comment by Lrs121** [comment]
Duplication can also occur by going to settings then to About then pressing the back button
