### ISSUE TITLE
Need supolicy support

### ISSUE THREAD

**Issue by HLFH** [seSuperuser/Superuser#16]
Hi,

I'm getting "supolicy command not found"

I would like to do `supolicy --live "allow kernel media_rw_data_file:file { read write };"` [to make DriveDroid work on OnePlus3T and OxygenOS](https://www.reddit.com/r/oneplus/comments/4y9vyp/op3_drivedroid/?st=ixoiwf4b&sh=256e0e89).

But I can't since your app does not implement this kind of command or am I wrong?

Thanks in advance,

**Comment by lbdroid** [comment]
Allowing a loaded/active policy to be altered on the fly is a very serious security vulnerability. I do NOT condone this type of behavior. If you require a customized policy, I suggest rebuilding your boot image with the altered policy.
