### ISSUE TITLE
Support for SD-Cards which are used as extension for the internal memory

### ISSUE THREAD

**Issue by Maaajaaa** [seSuperuser/Superuser#17]
Hi, I've rooted my XperiaSP with this [tool](https://forum.xda-developers.com/crossdevice-dev/sony/mod-boot-bridge-sony-elf-t3506883) and of course your supersu zip-file. The only problem is that the SuperSU App (me.phh.superuser) didn't get root access. A toast with Superuser denied to Superuser opened when I tried to change anything. 
So I checked for the su-binary which was where it's supposed to be and root via adb works as well. I located the package via `adb shell pm list packages -f | grep super` (after `adb root`) and got:   
`package:/mnt/expand/905fc766-2a1f-4c75-aa90-7ec2b413f7e0/app/me.phh.superuser-1/base.apk=me.phh.superuser`. So it's installed on the sd-card and not the internal memory. This can happen for others on other devices too.
There are two approches: 

1.  Move the app to the internal storage (probably better in case your SD doesn't work)
2. Or add the permissions for this installation to the su-communications.sh   

either way there should be a note on XDA and here (maybe also in the app in case that happens).

**Comment by SparkyCola** [comment]
the first solution worked for me (via Settings > Apps)

**Comment by janlovesit** [comment]
Cab I use this for Oppo F1s device?

**Comment by Maaajaaa** [comment]
What? moving the app to the internal memory? Just try it, same for the adb, if you have the same problem. They're both things that you can easily do and that shouldn't cause any issues.
