### ISSUE TITLE
Popup UI?

### ISSUE THREAD

**Issue by phhusson** [seSuperuser/Superuser#2]
It could be nice to have a (optionally?) popup interface on top of the app, instead of overlaying the whole application

**Comment by lbdroid** [comment]
I think in this you refer to the type of notification style used for things like incoming phone calls. Should be fairly trivial to implement this.

This type of notification is triggered when you create a notification with a priority of "high" or greater. We can include icon, title, details, and action buttons on the notification.

I'm not sure how many options we can keep in that kind of a notification. Current options are deny, allow this time, allow 10 minutes, allow forever. Might be a good idea to drop the remember options for that type of notification, keep it strictly limited to allow/deny. Only problem with this option is that it would make remembering authorizations impossible. This could probably be worked around by adding the option for remembering authorizations into the logger UI.

I have a fundamental problem with the "10 minute" option. Using it suggests that the user doesn't trust the application, in which case this adds a 10 minute window for an untrusted program to do bad things. The heads up notification also makes authorizations lighter, which means that repeatedly clicking "allow" shouldn't be as much of an issue as it would be with the full screen 5 second countdown.

Does the 5 second countdown actually do any good? It doesn't actually provide much in the way of useful information as it is (just the application name), and annoys you by making you wait for it.

**Comment by phhusson** [comment]
The 5 seconds countdown is to prevent to have an app show some text incitating the user to press on the location of the button and show the superuser popup "at the right moment"
5s might be a bit too much.
I also have a problem with the "10 minutes" option, but it's complicated. If we assume the selinux policy is secure, then it may make sense.

Popup's are just activities with transparent background, so we can draw whatever we want.

**Comment by lbdroid** [comment]
Things can still do damage within the confines of a secure selinux policy. For instance, deleting or changing things on the userdata partition.

I'm not sure what you mean by "we can draw whatever we want". If we use a high priority notification instead of a popup (which is what we should be doing in this case), we are held within the confines of that element of SystemUI. The nice thing is that the problem goes away with a high priority notification though, since it is designed to avoid that kind of problem.

**Comment by phhusson** [comment]
My "user" su policy aims at apps not having access to userdata. I don't know if it's an achievable aim though.

Ok understood for the high priority notification
