### ISSUE TITLE
Add temp on-the-fly unroot option

### ISSUE THREAD

**Issue by craigacgomez** [seSuperuser/Superuser#4]
There are several apps that do not work on root-enabled devices. While systemless root currently circumvents a majority of these currently, these apps may be updated in the future to not work with systemless root. What we need is a way to temporarily disable root on-the-fly without having to reboot the device and the re-enable root the on-the-fly as well. This would be achieved using an option in the Superuser app.

Another option would be to perhaps hide root based on a list of packages, though this would not work if the apps are looking for the binary instead of the asking for root access.

Perhaps, having both options would be great.

**Comment by lbdroid** [comment]
The ability to "hide" something depends on what is being used to detect it. If nothing exists to detect it, then we cannot hide it, since we cannot guess its methods.

More significant though, is that root *is* disabled, until the user actually enables it.

**Comment by craigacgomez** [comment]
I was thinking along these lines:
1. A list of root blacklisted packages. When any package in this blacklist requests root, do not grant root.
2. Temp unroot for package that look for the su binary that hides the su binary ( something like moving (renaming) the su binary randomly so that the package does not find it)

**Comment by lbdroid** [comment]
1) already done by default behavior.
2) root is a read-only FS.

**Comment by craigacgomez** [comment]
1) How do we expose this to the UI?
2) Derp! This is what happens when I multi task at times... Yes, we can't do this!

**Comment by lbdroid** [comment]
There is no reason to "expose" this to anything. Whenever *anything* executes 'su', unless that thing has previously been granted perpetual authorization, it will pop up an allow/deny dialog, which will allow the user to establish a permanent 'deny'.
