### ISSUE TITLE
Integrating Superuser app breaks Omnirom 6.0 build

### ISSUE THREAD

**Issue by Lrs121** [seSuperuser/Superuser#8]
Attempting to add the Superuser app to the build process of Omnirom 6.0 breaks the build process in a few ways.

After disabling the su build reference in system/extras/su and making sure the source is sync'd, to a location that omnirom recognizes, of packages/apps/Superuser and packages/apps/Widgets. Running a build with this source fails with undefined references. [Unmodified_Superuser-Omni-6_build_error.txt](https://github.com/seSuperuser/Superuser/files/121197/Unmodified_Superuser-Omni-6_build_error.txt)

After forking this repo and attempting to add the missing c files to the top level Android.mk file, [in this commit](https://github.com/Lrs121/Superuser/commit/c31ba3681e35de1e5efb332c4166ea6a64fe2a45) to correct the undefined references produced a new set of results. [Modified_Superuser-Omni-6_build_error.txt](https://github.com/seSuperuser/Superuser/files/121203/Modified_Superuser-Omni-6_build_error.txt)

I may be missing some key information if more information is needed please let me know and I'll attempt to gather what is needed.

**Comment by lbdroid** [comment]
Looks like it might needs some tweaks to the Android.mk for embedded building.

**Comment by Lrs121** [comment]
What kinds of tweaks? I've added hacks.c and bind.c to LOCAL_SRC_FILES producing the second log.

**Comment by lbdroid** [comment]
Drat, I looked at the first log but not the second one.

The error it shows (twice) is;
```
packages/apps/Superuser/Superuser/jni/su/hacks.c:24:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for(int i=0; i<(sizeof(apps_list)/sizeof(apps_list[0])); ++i) {
  ^
```

So what that means, is simply that you are not allowed to define your variable at that point in the program's code.

So with some context, you start with;
```
void hacks_init() {
	char oldCwd[512];
	getcwd(oldCwd, sizeof(oldCwd));
	chdir("/data/data");
	for(int i=0; i<(sizeof(apps_list)/sizeof(apps_list[0])); ++i) {
```

You just need to keep your variable declarations up at the very top of the function, BEFORE doing anything else, so like this;

```
void hacks_init() {
	char oldCwd[512];
        int i;
	getcwd(oldCwd, sizeof(oldCwd));
	chdir("/data/data");
	for(i=0; i<(sizeof(apps_list)/sizeof(apps_list[0])); ++i) {
```

**Comment by Lrs121** [comment]
That fixed the build. Im going to test it now and see if its working.
