### ISSUE TITLE
Cherry-pick CyanogenMod changes

### ISSUE THREAD

**Issue by wvengen** [seSuperuser/Superuser#9]
There are some changes in CyanogenMod's fork that could be useful to import.
https://github.com/seSuperuser/Superuser/compare/master...CyanogenMod:cm-12.0

**Comment by lbdroid** [comment]
A general comparison with a thousand useless translation commits isn't very helpful.

**Comment by wvengen** [comment]
Thanks for looking into this. I suppose you also saw the commits like c59e58dc3cc1c94c6ca0a37f2ee7de66e3021edb, 7c7a44d1c5689afa7c19f48e438625da12519ff8 and 2b782d197c4f09057bba9f3d7eceb722fbcf855d? (Though this is not an exhaustive list.)
For example, I needed the [selinux init changes](https://github.com/seSuperuser/Superuser/commit/7c7a44d1c5689afa7c19f48e438625da12519ff8) to get it work on lollipop when compiling it as part of an os image, for example (hope to contribute these changes back at some point).

**Comment by wvengen** [comment]
Just to clarify a bit more why I consider this issue to be relevant: there are some security-related commits. If would be helpful to know if these are relevant and applicable to this fork (I wouldn't be the best to judge), or if they aren't.

**Comment by polyzen** [comment]
@wvengen, those commits seem to already be in this repo? https://ptpb.pw/Ea0j.png

**Comment by wvengen** [comment]
@polyzen they are accessible from this repo (I guess Github looks in the network), but not present in any of the branches (or else these branch names would be shown as well). Searching this repo for the commit message doesn't reveal anything either.

**Comment by lbdroid** [comment]
Well, the clickjacking one is definitely there in the master branch, with a different id.
https://github.com/seSuperuser/Superuser/commit/c0fdfc206aef649255a117659bbec1b2b7402e22
* clickjacking is irrelevant though, since way forward is to use heads-up notifications.

The context one is meaningless, since we (a) don't use init.superuser.rc, (b) the context is bogus.

The "fix security" one is pretty obsolete, code has diverged dramatically since then.

**Comment by wvengen** [comment]
Ok, thanks for checking!

As a sidenote, I think init.superuser.rc is still relevant for including Superuser in a system image (like #8 if I am correct). No hurry here, though.

**Comment by lbdroid** [comment]
Not in the slightest bit relevant.
The daemon is loaded from init.rc -- https://github.com/seSuperuser/AOSP-SU-PATCH/blob/master/system_core.patch

**Comment by wvengen** [comment]
Ah! I guess I'm back to RTFM. Thanks.
